name: 'Aqua Security Trivy installer'
description: 'Install Trivy binary from release page'
author: 'Aqua Security'

inputs:
  version:
    description: 'Trivy version to install'
    required: false
    default: 'latest'
  path:
    description: 'Path in runner to install Trivy. Trivy will be installed in "trivy-dir" dir ("$HOME/.local/bin/trivy-dir/trivy" by default)'
    required: false
    default: '$HOME/.local/bin'
  cache:
    description: 'Used to specify whether caching is needed. Set to false, if you would like to disable caching.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Binary dir
      id: binary-dir
      shell: bash
      run: echo "dir=${{ inputs.path }}/trivy-dir" >> $GITHUB_OUTPUT

    - name: Checkout install script
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: aquasecurity/trivy
        sparse-checkout: |
          contrib/install.sh
        sparse-checkout-cone-mode: false
        path: trivy
        fetch-depth: 1

    - name: Binary version
      id: version
      shell: bash
      run: |
        if [ "${{ inputs.version }}" == "latest" ]; then
          cd trivy
          latest_tag=$(git describe --tags --abbrev=0)
          echo "version=$latest_tag" >> $GITHUB_OUTPUT
        else
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
        fi

    - name: Restore Trivy binary from cache
      if: ${{ inputs.cache == 'true' }}
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.binary-dir.outputs.dir }}
        key: trivy-binary-${{ steps.version.outputs.version }}-${{ runner.os }}-${{ runner.arch }}

    - name: Install Trivy
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "installing Trivy binary"
        bash ./trivy/contrib/install.sh -b ${{ steps.binary-dir.outputs.dir }} ${{ steps.version.outputs.version }}
        echo ${{ steps.binary-dir.outputs.dir }} >> $GITHUB_PATH