name: 'Aqua Security Trivy installer'
description: 'Install Trivy binary from release page'
author: 'Aqua Security'

inputs:
  version:
    description: 'Trivy version to install'
    required: false
    default: 'latest'
  path:
    description: 'Path in runner to install Trivy. Trivy will be installed in "trivy-dir" dir ("$HOME/.local/bin/trivy-dir/trivy" by default)'
    required: false
    default: '$HOME/.local/bin'
  cache:
    description: 'Used to specify whether caching is needed. Set to false, if you would like to disable caching.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout Trivy repo
      uses: actions/checkout@v4
      with:
        repository: aquasecurity/trivy
        path: trivy
        fetch-depth: 1

    - name: Install Trivy
      shell: bash
      run: |
        TRIVY_PATH="${{ inputs.path }}/trivy-dir"
        cat trivy/contrib/install.sh | bash -s -- -b $TRIVY_PATH ${{ inputs.version }}
        echo $TRIVY_PATH >> $GITHUB_PATH

    - name: Clean up Trivy repo
      shell: bash
      run: rm -r trivy